FROM bundenth/ray:latest AS base

FROM rocm/vllm-dev:navi_base_main_20250227 AS build
#FROM rocm/vllm:rocm6.4.1_vllm_0.10.0_20250812 AS build

# Get utils scripts
COPY --from=base /home/ray/workspace/ .

WORKDIR /home/ray/workspace

ENV RAY_EXPERIMENTAL_NOSET_ROCR_VISIBLE_DEVICES=1
ENV RAY_EXPERIMENTAL_NOSET_HIP_VISIBLE_DEVICES=1
ENV TOKENIZERS_PARALLELISM=false
ENV HIP_FORCE_DEV_KERNARG=1
ENV PYTORCH_ROCM_ARCH=gfx1100

# build vllm
RUN git clone https://github.com/vllm-project/vllm
WORKDIR /home/ray/workspace/vllm
RUN git fetch -v --prune -- origin v0.10.1
RUN pip install -U -r requirements/rocm.txt --no-cache-dir && \
    python setup.py bdist_wheel --dist-dir=dist
RUN pip install dist/*.whl --no-cache-dir

WORKDIR /home/ray/workspace

# build aiter
RUN git clone --recursive https://github.com/ROCm/aiter.git
WORKDIR /home/ray/workspace/aiter
RUN python setup.py develop 

# Build SGLang
WORKDIR /home/ray/workspace
RUN git clone -b v0.5.1.post3 https://github.com/sgl-project/sglang.git
# Compile sgl-kernel
# WORKDIR /home/ray/workspace/sglang/sgl-kernel
# RUN rm -f pyproject.toml \
#     && mv pyproject_rocm.toml pyproject.toml
# RUN python setup_rocm.py install
RUN pip install sgl-kernel
# Install sglang python package
WORKDIR /home/ray/workspace/sglang
RUN pip install -e "python[all_hip]" --no-cache-dir

# Install other dependencies
RUN sudo apt update && sudo apt install git bc wget -y && \
    sudo rm -rf /var/lib/apt/lists/*

WORKDIR /home/ray/workspace

COPY common_requirements.txt .
#RUN pip install -r common_requirements.txt --no-cache-dir

COPY run_model.sh .
RUN sudo chmod +x /home/ray/workspace/run_model.sh

# Performance environment variable.
# https://github.com/sgl-project/sglang/blob/main/docker/Dockerfile.rocm
# ENV HIP_FORCE_DEV_KERNARG=1
# ENV HSA_NO_SCRATCH_RECLAIM=1
# ENV SGLANG_SET_CPU_AFFINITY=1
# ENV SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN=1
# ENV NCCL_MIN_NCHANNELS=112
# ENV SGLANG_USE_AITER=1
# ENV SGLANG_MOE_PADDING=1
# ENV VLLM_FP8_PADDING=1
# ENV VLLM_FP8_ACT_PADDING=1
# ENV VLLM_FP8_WEIGHT_PADDING=1
# ENV VLLM_FP8_REDUCE_CONV=1
# ENV TORCHINDUCTOR_MAX_AUTOTUNE=1
# ENV TORCHINDUCTOR_MAX_AUTOTUNE_POINTWISE=1

CMD ["/bin/bash"]

