apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: watcher-api
  labels:
    kalavai.job.name: {{deployment_id}}
spec:
  interval: 10m
  chart:
    spec:
      chart: kalavai-watcher
      version: "{{watcher_version}}"
      sourceRef:
        kind: HelmRepository
        name: kalavai
        namespace: default
  values:
    image_tag: {{watcher_image_tag}}
    deployment:
      replicas: 1
      static_workspace: {{USER_ID}}
      is_shared_pool: False
      in_cluster: True
      admin_key: {{watcher_admin_key}}
      write_key: {{watcher_write_key}}
      readonly_key: {{watcher_readonly_key}}
      use_auth_key: True
    service:
      type: ClusterIP
    labels:
      kalavai.job.name: {{deployment_id}}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kalavai-api
  labels:
    kalavai.job.name: {{deployment_id}}
spec:
  interval: 10m
  chart:
    spec:
      chart: kalavai-api
      version: "{{kalavai_api_version}}"
      sourceRef:
        kind: HelmRepository
        name: kalavai
        namespace: default
  values:
    forced_namespace: {{USER_ID}}
    bridge:
      replicas: 1
      image_tag: {{kalavai_api_image_tag}}
      labels:
        kalavai.job.name: {{deployment_id}}
      enabled: true
      watcher_api_url: watcher-api-service:8000 #watcher-api-service.{{USER_ID}}.svc.cluster.local:8000
      watcher_api_key: {{watcher_admin_key}}
      service:
        type: ClusterIP
---
# expose kalavai api service
apiVersion: v1
kind: Service
metadata:
  name: pool-service
  labels:
    # must have this!
    kalavai.job.name: {{deployment_id}}
spec:
  type: NodePort
  selector:
    app: kalavai-api-app
  ports:
    - name: api
      port: 8000
      targetPort: 8000
      protocol: TCP