

FROM kalavai/ray-base:latest AS base

FROM rocm/pytorch:rocm6.4.1_ubuntu24.04_py3.12_pytorch_release_2.6.0

WORKDIR /home/ray/workspace

COPY --from=base /home/ray/workspace/ .

# : https://aphrodite.pygmalion.chat/installation/installation-rocm/

RUN  apt update &&  apt install -y git python3-dev sudo python3.12-venv hipblas

WORKDIR /home/ray/workspace

RUN python3 -m venv env

# dependencies
RUN pip install triton --root-user-action --no-cache-dir

RUN git clone https://github.com/PygmalionAI/aphrodite-engine.git && \
    cd aphrodite-engine && \
    sudo patch -t $(hipconfig --rocmpath)/lib/llvm/lib/clang/*/include/__clang_hip_cmath.h ./patches/amd.patch

RUN . env/bin/activate && \
    cd aphrodite-engine && \
    pip install -U -r requirements/rocm.txt --no-cache-dir && \
    python setup.py develop

COPY run_model.sh .

RUN chmod +x /home/ray/workspace/run_model.sh