apiVersion: v1
kind: Namespace
metadata:
  name: kube-watcher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-watcher-api
  namespace: kube-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-watcher-api
  template:
    metadata:
      labels:
        app: kube-watcher-api
    spec:
      containers:
      - name: kube-watcher-api
        image: bundenth/kube_watcher:v8
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8000
        env:
        - name: PROMETHEUS_ENDPOINT
          value: "http://10.152.183.108:9090"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-watcher-nodeport
  namespace: kube-watcher
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: kube-watcher-api