apiVersion: v1
kind: Namespace
metadata:
  name: kube-watcher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-watcher-api
  namespace: kube-watcher
spec:
  replicas: 2 # ensure there is minimal downtime if node goes down
  selector:
    matchLabels:
      app: kube-watcher-api
  template:
    metadata:
      labels:
        app: kube-watcher-api
    spec:
      containers:
      - name: kube-watcher-api
        image: bundenth/kube_watcher:v12
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8000
        env:
        - name: PROMETHEUS_ENDPOINT
          value: "http://10.152.183.239"
        - name: OPENCOST_ENDPOINT
          value: "http://10.152.183.93:9003"
        - name: ANVIL_CLIENT_KEY
          value: "client_A2ZZVMV6LLHVCZ4XSMTOWTSH-ADMVMYW5OIRPH75P"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-watcher-nodeport
  namespace: kube-watcher
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30873
  selector:
    app: kube-watcher-api
