apiVersion: v1
kind: Namespace
metadata:
  name: kalavai-system
---
# Cluster roles and service account permissions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: kalavai-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-cluster-role
  namespace: kalavai-system
rules:
  - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
    resources:
      - pods
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-cluster-role-binding
subjects:
- namespace: kalavai-system 
  kind: ServiceAccount
  name: api-service-account 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-cluster-role 
---
## Service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-watcher-api
  namespace: kalavai-system
spec:
  replicas: 2 # ensure there is minimal downtime if node goes down
  selector:
    matchLabels:
      app: kube-watcher-api
  template:
    metadata:
      labels:
        app: kube-watcher-api
    spec:
      containers:
      - name: kube-watcher-api
        image: bundenth/kube_watcher:v24
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8000
        env:
        - name: PROMETHEUS_ENDPOINT
          value: "http://10.43.100.250"
        - name: OPENCOST_ENDPOINT
          value: "http://10.43.140.3:9003"
        - name: IN_CLUSTER
          value: "True"
        - name: KW_USE_AUTH
          value: "True"
        - name: KW_MASTER_KEY
          value: "CARLOS_ANNIE_ADAM_KALAVAI"
      serviceAccountName: api-service-account  # Service account with cluster permissions
---
apiVersion: v1
kind: Service
metadata:
  name: kube-watcher-service
  namespace: kalavai-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: kube-watcher-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tools-library-ingress
  namespace: kalavai-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  rules:
    # Add a DNS record to match this URL to the IP of the cluster
    - host: kubeapi.test.k8s.mvp.kalavai.net
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: kube-watcher-service
                port:
                  number: 80
            path: /
  tls:
  - hosts:
    - kubeapi.test.k8s.mvp.kalavai.net
    secretName: kubeapi.test.k8s.mvp.kalavai.net-tls
