apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sparse-model
  namespace: carlosfm
  labels:
    deepsparse: model
spec:
  replicas: 1
  selector:
    matchLabels:
      deepsparse: model
  template:
    metadata:
      labels:
        deepsparse: model
    spec:
      containers:
      - name: deepsparse-container
        image: ghcr.io/neuralmagic/deepsparse:v1.6.1
        command: ["sh", "-c"]
        args:
        - |
          deepsparse.server --task chat --model_path "zoo:mpt-7b-dolly_mpt_pretrain-pruned50_quantized" --num-cores 2
        resources:
          limits:
            cpu: 2
            memory: 8Gi 
            ephemeral-storage: "24Gi"
          requests:
            cpu: 2 # must accommodate num-cores requested for execution
            memory: 8Gi # must accommodate for the model's weights
            ephemeral-storage: "24Gi"
      restartPolicy: Always