apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: flex
  labels:
    # must have this label
    kalavai.job.name: flex
spec:
  schedulerName: volcano
  plugins:
    env: []
    svc: ["--disable-network-policy=true"]
  tasks:
  - replicas: 1   # One ps pod specified
    name: worker
    policies:
    - event: PodEvicted
      action: RestartTask
    - event: TaskCompleted
      action: CompleteJob
    template: # Definition of the ps pod
      metadata:
        labels:
          kalavai.job.name: flex
          role: leader
      spec:
        containers:
        - name: container
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
          - sh
          - -c
          - |
            sleep 1;
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 1
              memory: 2Gi