apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: {{deployment_id}}
  labels:
    # must have this label
    kalavai.job.name: {{deployment_id}}
spec:
  queue: default
  schedulerName: volcano
  plugins:
    env: []
    svc: ["--disable-network-policy=true"]
  maxRetries: {{max_retries}}
  tasks:
{% if litellm_key != "" %}
  - replicas: 1   # One ps pod specified
    name: registrar
    policies:
    - event: PodEvicted
      action: RestartTask
    - event: PodFailed
      action: RestartTask
    - event: TaskCompleted
      action: RestartTask
    - event: Unknown
      action: RestartTask
    template: # Definition of the ps pod
      terminationGracePeriodSeconds: 30 #give enough time to the preStop hook
      metadata:
        labels:
          kalavai.job.name: {{deployment_id}}
      spec:
        {% if NODE_SELECTORS %}
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
            {% if NODE_SELECTORS_OPS == "OR" %}
              {% for selector in NODE_SELECTORS %}
              - matchExpressions:
                - key: {{selector.name}}
                  operator: In
                  values:
                  {% for vals in selector.value %}
                  - "{{vals}}"
                  {% endfor %}
              {% endfor %}
            {% else %}
              - matchExpressions:
              {% for selector in NODE_SELECTORS %}
                {% for vals in selector.value %}
                - key: {{selector.name}}
                  operator: In
                  values:
                  - "{{vals}}"
                {% endfor %}
              {% endfor %}
            {% endif %}
        {% endif %}
        containers:
        - name: registrar-leader
          image: docker.io/bundenth/kalavai-utils:latest
          command:
          - sh
          - -c
          - |
            echo "Waiting for model to be served..."
            PS_HOST=`cat /etc/volcano/server.host`;
            /workspace/wait_for_service.sh --servers="$PS_HOST" --port=8080
            export MODEL_API_BASE="http://"$PS_HOST"."$VC_NAMESPACE":8080/v1";
            /workspace/start_point.sh \
              --litellm_kalavai_extras='{{litellm_kalavai_extras}}' \
              --litellm_access_group={{litellm_access_group}}
          env:
          - name: VC_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LITELLM_MODEL_NAME
          {% if model_name_override != "" %}
            value: "{{model_name_override}}"
          {% else %}
            value: "{{model_filename}}"
          {% endif %}
          - name: LITELLM_BASE_URL
            value: {{litellm_base_url}}
          - name: LITELLM_KEY
            value: {{litellm_key}}
          - name: MODEL_ID
            value: {{model_filename}}
          - name: DEPLOYMENT_ID
            value: {{deployment_id}}
          - name: PROVIDER
            value: openai
          lifecycle:
            preStop:
              exec:
                command: 
                - sh
                - -c
                - |
                  /workspace/cleanup.sh
          resources:
            requests:
              cpu: 0.05
              memory: 0.05Gi
            limits:
              cpu: 0.05
              memory: 0.05Gi
        restartPolicy: OnFailure
{% endif %}
  - replicas: 1   # One ps pod specified
    name: server
    policies:
    - event: PodEvicted
      action: RestartJob
    - event: PodFailed
      action: RestartJob
    - event: TaskCompleted
      action: RestartJob
    - event: Unknown
      action: RestartJob
    template: # Definition of the ps pod
      metadata:
{% if gpus > 0 %}
        annotations:
          # must have these annotations
          {{nouse_gputype}}
          {{use_gputype}}
{% endif %}
        labels:
          role: leader
          kalavai.job.name: {{deployment_id}}
      spec:
{% if gpus > 0 %}
        runtimeClassName: nvidia
{% endif %}
        {% if NODE_SELECTORS %}
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
            {% if NODE_SELECTORS_OPS == "OR" %}
              {% for selector in NODE_SELECTORS %}
              - matchExpressions:
                - key: {{selector.name}}
                  operator: In
                  values:
                  {% for vals in selector.value %}
                  - "{{vals}}"
                  {% endfor %}
              {% endfor %}
            {% else %}
              - matchExpressions:
              {% for selector in NODE_SELECTORS %}
                {% for vals in selector.value %}
                - key: {{selector.name}}
                  operator: In
                  values:
                  - "{{vals}}"
                {% endfor %}
              {% endfor %}
            {% endif %}
        {% endif %}
        containers:
        - name: llamacpp-leader
{% if gpus > 0 %}
          image: docker.io/bundenth/llamacpp-gpu:latest
{% else %}
          image: docker.io/bundenth/llamacpp-cpu:latest
{% endif %}
          command:
          - sh
          - -c
          - |
{% if gpus > 0 %}
            /workspace/build.sh server_gpu;
{% else %}
            /workspace/build.sh server_cpu;
{% endif %}
            HOSTS=`cat /etc/volcano/worker.host`;
            export WORKERS=$(/workspace/get_workers_address.sh --rpc_port={{rpc_port}} --rpc_servers="${HOSTS}")
            /workspace/run_api_server.sh \
              --repo_id={{repo_id}} \
              --model_filename={{model_filename}} \
              --local_dir=/cache \
              --port=8080 \
              --rpc_servers=$WORKERS \
              --parallel={{parallel}} \
              --extra='{{server_extra}}'
          env:
          - name: HF_TOKEN
            value: {{hf_token}}
          ports:
          - containerPort: 8080
            name: model-port
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: {{cpus}}
              memory: {{memory}}Gi
              ephemeral-storage: {{working_memory}}Gi
{% if gpus > 0 %}
              nvidia.com/gpu: {{gpus}}
{% endif %}
            limits:
              cpu: {{cpus}}
              memory: {{memory}}Gi
              ephemeral-storage: {{working_memory}}Gi
{% if gpus > 0 %}
              nvidia.com/gpu: {{gpus}}
              nvidia.com/gpumem-percentage: {{cuda_gpu_mem_percentage}}
{% endif %}
          volumeMounts:
            - name: cache
              mountPath: /cache
        volumes:
        - name: cache
          emptyDir: {}
        restartPolicy: OnFailure
  - replicas: {{workers - 1}}
    name: worker
    policies:
    - event: PodEvicted
      action: RestartJob
    - event: PodFailed
      action: RestartJob
    - event: TaskCompleted
      action: RestartJob
    - event: Unknown
      action: RestartJob
    template: # Definition of worker pods
      metadata:
        labels:
          kalavai.job.name: {{deployment_id}}
      spec:
{% if gpus > 0 %}
        runtimeClassName: nvidia
{% endif %}
        {% if NODE_SELECTORS %}
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
            {% if NODE_SELECTORS_OPS == "OR" %}
              {% for selector in NODE_SELECTORS %}
              - matchExpressions:
                - key: {{selector.name}}
                  operator: In
                  values:
                  {% for vals in selector.value %}
                  - "{{vals}}"
                  {% endfor %}
              {% endfor %}
            {% else %}
              - matchExpressions:
              {% for selector in NODE_SELECTORS %}
                {% for vals in selector.value %}
                - key: {{selector.name}}
                  operator: In
                  values:
                  - "{{vals}}"
                {% endfor %}
              {% endfor %}
            {% endif %}
        {% endif %}
        containers:
        - name: llamacpp-worker
{% if gpus > 0 %}
          image: docker.io/bundenth/llamacpp-gpu:latest
{% else %}
          image: docker.io/bundenth/llamacpp-cpu:latest
{% endif %}
          command:
          - sh
          - -c
          - |
{% if gpus > 0 %}
            /workspace/build.sh gpu;
{% else %}
            /workspace/build.sh cpu;
{% endif %}
            /workspace/run_rpc_worker.sh --rpc_port={{rpc_port}}
          env:
          - name: HF_TOKEN
            value: {{hf_token}}
          resources:
            requests:
              cpu: {{cpus}}
              memory: {{memory}}Gi
{% if gpus > 0 %}
              nvidia.com/gpu: {{gpus}}
{% endif %}
            limits:
              cpu: {{cpus}}
              memory: {{memory}}Gi
{% if gpus > 0 %}
              nvidia.com/gpu: {{gpus}}
              nvidia.com/gpumem-percentage: {{cuda_gpu_mem_percentage}}
{% endif %}
        restartPolicy: OnFailure
---
# deploy NodePort to expose model (if not using LiteLLM registration)
{% if litellm_key == "" %}
apiVersion: v1
kind: Service
metadata:
  name: {{deployment_id}}-service
  labels:
    # must have this!
    kalavai.job.name: {{deployment_id}}
spec:
  type: NodePort
  selector:
    role: leader
    kalavai.job.name: {{deployment_id}}
  ports:
    - name: main
      port: 8080
      targetPort: 8080
      protocol: TCP
    {% if nodeport != "" %}
      nodePort: {{nodeport}}
    {% endif %}
{% endif %}