############################
## MUST HAVE THESE FIELDS ##
- name: id_field
  value: model_filename
  default: model_filename
  description: "Field that contains the ID of the job"

# must contain the list of ports to enable in the leader node
- name: endpoint_ports
  value: "8080"
  default: "8080"
  description: "[DO NOT CHANGE] Ports opened on master node (will be shown as endpoints for the job)"
############################

- name: working_memory
  value: 5
  default: 5
  description: "Temporary storage to use to cache model weights (in GB)"

- name: litellm_base_url
  value: "http://litellm.default.svc.cluster.local:4000" #"http://192.168.68.67:30219"
  default: "http://litellm.default.svc.cluster.local:4000"
  description: "Base URL of the LiteLLM service (central registry)"

- name: litellm_key
  value: ""
  default: ""
  description: "Master key of the LiteLLM service (central registry)"

- name: cpu_workers
  value: 1
  default: 1
  description: "Number of remote workers"

- name: gpu_workers
  value: 0
  default: 0
  description: "Number of remote workers"

- name: repo_id
  value: null
  default: null
  description: "Huggingface model id to load"

- name: model_filename
  value: "None"
  default: "None"
  description: "Specific model file to use (handy for quantized models such as gguf)"

- name: hf_token
  value: <yout token>
  default: null
  description: "Huggingface token, required to load model weights"

- name: cpus
  value: "2"
  default: "2"
  description: "CPUs per single worker (final one = cpus * num_workers)"

- name: memory
  value: "4"
  default: "4"
  description: "RAM memory per single worker (final one = memory * num_workers)"

- name: rpc_port
  value: "50052"
  default: "50052"
  description: "RAM memory per single worker (final one = memory * num_workers)"

- name: server_extra
  value: ""
  default: ""
  description: "Extra parameters for deployment. See https://github.com/ggerganov/llama.cpp/tree/master/examples/server"
