############################
## MUST HAVE THESE FIELDS ##
- name: id_field
  value: model_filename
  default: model_filename
  editable: false
  required: false
  description: "Field that contains the ID of the job"

# must contain the list of ports to enable in the leader node
- name: endpoint_ports
  value: "8080"
  default: "8080"
  editable: false
  required: false
  description: "[DO NOT CHANGE] Ports opened on master node (will be shown as endpoints for the job)"

- name: rpc_port
  value: "50052"
  default: "50052"
  editable: false
  required: false
  description: "Default port for the RPC server"
############################

- name: working_memory
  value: 5
  default: 5
  editable: true
  required: true
  description: "Temporary storage to use to cache model weights (in GB), should be big enough to hold the model weights. All workers should have enough free disk to accommodate the weights."

- name: litellm_base_url
  value: "http://litellm.default.svc.cluster.local:4000" #"http://192.168.68.67:30219"
  default: "http://litellm.default.svc.cluster.local:4000"
  editable: true
  required: false
  description: "Base URL of the LiteLLM service (central model registry). This can be an external LiteLLM instance or an internal deployment in the pool (default)"

- name: litellm_key
  value: ""
  default: ""
  editable: true
  required: false
  description: "Master key of the LiteLLM service (central model registry)"

- name: workers
  value: 1
  default: 1
  editable: true
  required: true
  description: "Number of workers, corresponding to the number of nodes (or machines) that will be used to deploy the model"

- name: repo_id
  value: null
  default: null
  editable: true
  required: true
  description: "Huggingface model id to deploy"

- name: model_filename
  value: null
  default: null
  editable: true
  required: true
  description: "Specific GGUF model file to use, which let's you select the quantization level"

- name: hf_token
  value: <yout token>
  default: null
  editable: true
  required: true
  description: "Huggingface access token, only required to load gated model weights"

- name: cpus
  value: 2
  default: 2
  editable: true
  required: false
  description: "CPUs to be used per single worker (final one = cpus * workers). Workers should have these many CPUs available."

- name: gpus
  value: 0
  default: 0
  editable: true
  required: false
  description: "GPUs to be used per single worker (final one = gpus * workers). Workers should have these many GPUs available."

- name: memory
  value: 4
  default: 4
  editable: true
  required: false
  description: "RAM memory to be used per single worker (final one = memory * workers). Workers should have these much RAM available."

- name: server_extra
  value: ""
  default: ""
  editable: true
  required: false
  description: "Extra parameters for deployment. See https://github.com/ggerganov/llama.cpp/tree/master/examples/server"

- name: max_retries
  value: 1000
  default: 1000
  editable: true
  required: false
  description: "If the job fails, how many times to retry redeployment"