apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-cluster-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
        - networking.k8s.io
        - leaderworkerset.x-k8s.io
        - ray.io
    resources:
      - pods
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingresses
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
      - secrets
      - statefulsets
      - statefulsets/apps
      - leaderworkersets
      - leaderworkersets/status
      - pods/log
      - pods/eviction
      - rayclusters
      - rayclusters/status
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]