apiVersion: v1
kind: Service
metadata:
  name: kube-watcher-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: kube-watcher-api