apiVersion: v1
kind: Service
metadata:
  name: kube-watcher-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31000
  selector:
    app: kube-watcher-api