############################
## MUST HAVE THESE FIELDS ##
- name: id_field
  value: mode
  default: mode
  editable: false
  required: false
  description: "Field that contains the ID of the job"

# must contain the list of ports to enable in the leader node
- name: endpoint_ports
  value: "8080"
  default: "8080"
  editable: false
  required: false
  description: "[DO NOT CHANGE] Ports opened on master node (will be shown as endpoints for the job)"
############################

- name: mode
  value: "stt"
  default: "tts"
  editable: true
  required: true
  description: "Model mode, whether to use speach to text (stt) or text to speech (tts)"

- name: hf_token
  value: ""
  default: "<your token>"
  editable: true
  required: true
  description: "Huggingface access token, required for gated models"