apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: {{deployment_id}}
  labels:
    # must have this label
    kalavai.job.name: {{deployment_id}}
spec:
  queue: default
  #minAvailable: 2
  schedulerName: volcano
  plugins:
    env: []
    svc: []
  policies: 
  - event: PodEvicted # Restart the job when a pod is evicted.
    action: RestartJob
  tasks:
  - replicas: 1   # One ps pod specified
    name: ps
    template: # Definition of the ps pod
      spec:
        containers:
        - name: nginx
          # docker image to use as base for each worker
          image: nginx:1.14.2
          # what resources each worker should have
          resources:
            limits:
              cpu: "100m"
              memory: "1Gi"
              nvidia.com/gpu: "1"
            requests:
              cpu: "50m"
              memory: "1Gi"
              nvidia.com/gpu: "1"
          ports:
          # what port to make available
          # to make them available through job endpoints, make sure you list the ports in values.yaml, under endpoint_ports
          - containerPort: 8080
        restartPolicy: Never