# example: https://raw.githubusercontent.com/ray-project/ray/master/doc/source/cluster/kubernetes/configs/ray-cluster.gpu.yaml
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: {{deployment_id}}
  labels:
    # must have this label
    kalavai.job.name: {{deployment_id}}
  annotations:
    # fault tolerance https://ray-project.github.io/kuberay/guidance/gcs-ft/
    #ray.io/ft-enabled: "true" # <- add this annotation enable GCS FT
    #ray.io/external-storage-namespace: "raycluster-storage" # <- optional, to specify the external storage namespace
spec:
  rayVersion: "{{ray_version}}"
  autoscalerOptions:
    # upscalingMode is "Default" or "Aggressive."
    # Conservative: Upscaling is rate-limited; the number of pending worker pods is at most the size of the Ray cluster.
    # Default: Upscaling is not rate-limited.
    # Aggressive: An alias for Default; upscaling is not rate-limited.
    upscalingMode: {{upscaling_mode}}
    # idleTimeoutSeconds is the number of seconds to wait before scaling down a worker pod which is not using Ray resources.
    idleTimeoutSeconds: {{idle_timeout_seconds}}
  enableInTreeAutoscaling: true
  headGroupSpec:
    serviceType: ClusterIP #NodePort
    rayStartParams:
      dashboard-host: "0.0.0.0"
      num-cpus: "0" # avoid workload on head
    template: # Pod template
      metadata:
        labels:
          kalavai.job.name: {{deployment_id}}
      spec: # Pod spec
        nodeSelector:
          kalavai/role: server
        restartPolicy: Always
        containers:
        - name: ray-head
          image: docker.io/rayproject/ray:{{ray_version}}-py{{python_version}}-{{cuda_version}}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: {{cpus}}
              memory: {{memory}}Gi
            requests:
              cpu: {{cpus}}
              memory: {{memory}}Gi
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          - containerPort: 8000
            name: serve
  workerGroupSpecs:
  # worker group of up to 4 GPU workers
  - groupName: gpu-group
    replicas: {{workers}}
    minReplicas: {{min_workers}}
    maxReplicas: {{max_workers}}
    rayStartParams: 
    #  num-gpus: "{{gpus}}"
    template:
      metadata:
        labels:
          kalavai.job.name: {{deployment_id}}
      spec:
      {% if NODE_SELECTORS %}
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
            {% if NODE_SELECTORS_OPS == "OR" %}
              {% for selector in NODE_SELECTORS %}
              - matchExpressions:
                - key: {{selector.name}}
                  operator: In
                  values:
                  {% for vals in selector.value %}
                  - "{{vals}}"
                  {% endfor %}
              {% endfor %}
            {% else %}
              - matchExpressions:
              {% for selector in NODE_SELECTORS %}
                {% for vals in selector.value %}
                - key: {{selector.name}}
                  operator: In
                  values:
                  - "{{vals}}"
                {% endfor %}
              {% endfor %}
            {% endif %}
        {% endif %}
        containers:
        - name: ml-work-group
          image: docker.io/rayproject/ray:{{ray_version}}-py{{python_version}}-{{cuda_version}}
          runtimeClassName: nvidia
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              nvidia.com/gpu: {{gpus}}
              nvidia.com/gpumem-percentage: {{cuda_gpu_mem_percentage}}
              cpu: {{cpus}}
              memory: {{memory}}Gi
            requests:
              nvidia.com/gpu: {{gpus}}
              nvidia.com/gpumem-percentage: {{cuda_gpu_mem_percentage}}
              cpu: {{cpus}}
              memory: {{memory}}Gi
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
---
# deploy NodePorts to expose cluster
apiVersion: v1
kind: Service
metadata:
  name: {{deployment_id}}-service
  labels:
    # must have this!
    kalavai.job.name: {{deployment_id}}
spec:
  type: NodePort
  selector:
    # points at the svc created by the cluster
    ray.io/node-type: head
    ray.io/cluster: {{deployment_id}}
    ray.io/identifier: {{deployment_id}}-head
  ports:
    - name: gcs
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: dashboard
      port: 8265
      targetPort: 8265
      protocol: TCP
    - name: client
      port: 10001
      targetPort: 10001
      protocol: TCP
    - name: serve
      port: 8000
      targetPort: 8000
      protocol: TCP
