apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: {{deployment_id}}
  labels:
    # must have this label
    kalavai.job.name: {{deployment_id}}
spec:
  minAvailable: 2
  schedulerName: volcano
  plugins:
    env: []
    svc: ["--disable-network-policy=true"]
  tasks:
  {% if external_postgreSQL_url == "" %}
  - replicas: 1   # One ps pod specified
    name: db
    policies:
    - event: PodEvicted
      action: RestartJob
    - event: PodFailed
      action: RestartJob
    - event: TaskCompleted
      action: RestartJob
    - event: Unknown
      action: RestartJob
    template: # Definition of the ps pod
      metadata:
        labels:
          kalavai.job.name: {{deployment_id}}
      spec:
      {% if NODE_SELECTORS %}
        nodeSelector:
        {% for selector in NODE_SELECTORS %}
          {{selector.name}}: {{selector.value}}
        {% endfor %}
      {% endif %}
        containers:
        - name: postgres
          image: 'postgres:14'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: {{postgres_db}}
          - name: POSTGRES_USER
            value: {{postgres_user}}
          - name: POSTGRES_PASSWORD
            value: {{postgres_password}}
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdata"
          resources:
            requests:
              cpu: {{cpus}}
              memory: {{memory}}Gi
            limits:
              cpu: {{cpus}}
              memory: {{memory}}Gi
  {% endif %}
  - replicas: {{replicas}}   # One ps pod specified
    name: server
    policies:
    - event: PodEvicted
      action: RestartTask
    - event: PodFailed
      action: RestartTask
    - event: TaskCompleted
      action: RestartTask
    - event: Unknown
      action: RestartTask
    template: # Definition of the ps pod
      metadata:
        labels:
          role: leader
          kalavai.job.name: {{deployment_id}}
      spec:
      {% if NODE_SELECTORS %}
        nodeSelector:
        {% for selector in NODE_SELECTORS %}
          {{selector.name}}: {{selector.value}}
        {% endfor %}
      {% endif %}
        containers:
        - image: docker.io/bundenth/litellm:latest
          name: litellm-server
          command:
          - sh
          - -c
          - |
            DB_HOST=`cat /etc/volcano/db.host`;
          {% if external_postgreSQL_url == "" %}
            export DATABASE_URL=postgres://{{postgres_user}}:{{postgres_password}}@$DB_HOST:5432/{{postgres_db}}
          {% else %}
            export DATABASE_URL={{external_postgreSQL_url}}
          {% endif %}
            litellm --port 4000 --config /workspace/config.yaml
          ports:
          - containerPort: 4000
            name: lite-port
          env:
          - name: LITELLM_LOG
            value: ERROR
          - name: LITELLM_MASTER_KEY
            value: {{master_key}}
          - name: LITELLM_SALT_KEY
            value: {{salt_key}}
          - name: STORE_MODEL_IN_DB
            value: "True"
          - name: PORT
            value: "4000"
          - name: DISABLE_ADMIN_UI
            value: "{{disable_admin_ui}}"
          - name: UI_USERNAME
            value: "{{ui_username}}"
          - name: UI_PASSWORD
            value: "{{ui_password}}"
          - name: LANGFUSE_PUBLIC_KEY
            value: "{{langfuse_public_key}}"
          - name: LANGFUSE_SECRET_KEY
            value: "{{langfuse_secret_key}}"
          - name: LANGFUSE_HOST
            value: "{{langfuse_host}}"
          resources:
            requests:
              cpu: {{cpus}}
              memory: {{memory}}Gi
            limits:
              cpu: {{cpus}}
              memory: {{memory}}Gi
  
