- name: deployment_name
  value: diffusers
  default: diffusers
  editable: true
  required: true
  description: "Name of the deployment job"

- name: working_memory
  value: 30
  default: 5
  editable: true
  required: true
  description: "Temporary storage to use to cache model weights (in GB), should be big enough to hold the model weights. All workers should have enough free disk to accommodate the weights."

- name: workers
  value: 1
  default: 1
  editable: true
  required: true
  description: "Number of workers, corresponding to the number of nodes (or machines) that will be used to deploy the model"

- name: min_replicas
  value: 0
  default: 0
  editable: true
  required: false
  description: "Minimum number of model replicas to be loaded at any given time"

- name: max_replicas
  value: 1
  default: 1
  editable: true
  required: false
  description: "Maximum number of model replicas to be loaded at any given time"

- name: hf_token
  value: ""
  default: null
  editable: true
  required: true
  description: "Huggingface access token, only required to load gated model weights"

- name: cpus
  value: 2
  default: 2
  editable: true
  required: false
  description: "Number of cpus per worker"

- name: memory
  value: 16
  default: 4
  editable: true
  required: false
  description: "Memory per worker"

- name: gpus
  value: 1
  default: 1
  editable: true
  required: false
  description: "Number of gpus per worker"

- name: litellm_base_url
  value: "http://litellm.default.svc.cluster.local:4000"
  default: "http://litellm.default.svc.cluster.local:4000"
  editable: true
  required: false
  description: "Base URL of the LiteLLM service (central registry)"

- name: litellm_key
  value: ""
  default: ""
  editable: true
  required: false
  description: "Master key of the LiteLLM service (central registry)"