############################
### MUST HAVE THESE FIELDS ##
- name: id_field
  value: deployment_name
  default: deployment_name
  editable: false
  required: false
  description: "Field that contains the ID of the job"
############################

- name: deployment_name
  value: "litellm-registrar" 
  default: "litellm-registrar"
  editable: true
  required: true
  description: "Name of the job"

- name: model_id
  value: null
  default: null
  editable: true
  required: true
  description: "Huggingface model id to deploy"

- name: model_api_base
  value: ""
  default: ""
  editable: true
  required: true
  description: "Base URL for the model"

- name: litellm_base_url
  value: "http://litellm.default.svc.cluster.local:4000" #"http://192.168.68.67:30219"
  default: "http://litellm.default.svc.cluster.local:4000"
  editable: true
  required: false
  description: "Base URL of the LiteLLM service (central model registry). This can be an external LiteLLM instance or an internal deployment in the pool (default)"

- name: litellm_key
  value: ""
  default: ""
  editable: true
  required: false
  description: "Master key of the LiteLLM service (central model registry)"

- name: litellm_access_group
  value: ""
  default: ""
  editable: true
  required: false
  description: "What access group to assign the model to (ringfencing)"

- name: litellm_kalavai_extras
  value: "{}"
  default: "{}"
  editable: true
  required: false
  description: "Extra information to store in the LiteLLM model registration (must be a dictionary)"

- name: model_name_override
  value: ""
  default: ""
  editable: true
  required: false
  description: "Model name to use (defaults to model_id) during inference"

- name: lago_url
  value: ""
  default: ""
  editable: true
  required: false
  description: "Base URL of the Lago service (payment system)"

- name: lago_api_key
  value: ""
  default: ""
  editable: true
  required: false
  description: "Master key of the Lago service"

- name: lago_external_subscription_id
  value: ""
  default: ""
  editable: true
  required: false
  description: "ID of the Lago subscription to send events to"

- name: lago_event_code
  value: ""
  default: ""
  editable: true
  required: false
  description: "Event code to use when submitting event to Lago payment API"

- name: lago_event_interval
  value: ""
  default: ""
  editable: true
  required: false
  description: "Interval in seconds to send the lago event"

- name: max_retries
  value: 1000
  default: 1000
  editable: true
  required: false
  description: "If the job fails, how many times to retry redeployment"

- name: rpm_limit
  value: 50000
  default: 50000
  editable: true
  required: false
  description: "Max Requests per Minute allowed for this model to handle"