FROM bundenth/ray:latest AS base

FROM rocm/vllm:rocm6.4.1_vllm_0.10.0_20250812 AS build

WORKDIR /home/ray/workspace

# Get utils scripts
COPY --from=base /home/ray/workspace/ .

RUN sudo apt update && sudo apt install bc wget ffmpeg curl -y && \
    sudo rm -rf /var/lib/apt/lists/*

RUN pip install ray[serve-grpc,default]==2.43.0 --no-cache-dir

COPY common_requirements.txt .
RUN pip install -r common_requirements.txt --no-cache-dir && \
    rm -rf /home/ray/.cache/pip

COPY run_model.sh .
RUN sudo chmod +x /home/ray/workspace/run_model.sh

