# # reference https://github.com/vllm-project/vllm/blob/936416e5e4bf72d412d7317398935b66a100716f/docker/Dockerfile.rocm
FROM kalavai/ray-base:latest AS base

#FROM rocm/vllm:rocm6.4.1_vllm_0.9.1_20250715
FROM rocm/vllm:rocm6.4.1_vllm_0.10.1_20250909
WORKDIR /home/ray/workspace

# Get utils scripts
COPY --from=base /home/ray/workspace/ .

RUN sudo apt update && sudo apt install bc wget ffmpeg curl -y && \
    sudo rm -rf /var/lib/apt/lists/*

# install dependencies
COPY common_requirements.txt .
RUN pip install -r common_requirements.txt --no-cache-dir
# RUN pip install ray[default,serve-grpc]==2.44.1 --no-cache-dir

# install cupy (required for pipeline parallelism)
ENV CUPY_INSTALL_USE_HIP=1
ENV ROCM_HOME=/opt/rocm
ENV HCC_AMD_GPU_TARGET=gfx1100
RUN pip install cupy --no-cache-dir

COPY run_model.sh .
RUN sudo chmod +x /home/ray/workspace/run_model.sh

# Fix for 'HIP error: invalid device ordinal' with Ray on ROCm. See #21457, #12572
ENV RAY_EXPERIMENTAL_NOSET_ROCR_VISIBLE_DEVICES=1
ENV RAY_EXPERIMENTAL_NOSET_HIP_VISIBLE_DEVICES=1
# Performance variables
ENV SAFETENSORS_FAST_GPU=1
ENV HIP_FORCE_DEV_KERNARG=1

CMD ["/bin/bash"]


