apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: {{deployment_id}}
  labels:
    # must have this label
    kalavai.job.name: {{deployment_id}}
spec:
  queue: default
  schedulerName: volcano
  plugins:
    env: []
    svc: ["--disable-network-policy=true"]
  maxRetry: {{max_retries}}
  tasks:
{% if litellm_key != "" %}
  - replicas: 1   # One ps pod specified
    name: registrar
    policies:
    - event: PodEvicted
      action: RestartTask
    - event: PodFailed
      action: RestartTask
    - event: TaskCompleted
      action: RestartTask
    - event: Unknown
      action: RestartTask
    template: # Definition of the ps pod
      terminationGracePeriodSeconds: 30 #give enough time to the preStop hook
      metadata:
        labels:
          kalavai.job.name: {{deployment_id}}
      spec:
      {% if NODE_SELECTORS %}
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
            {% if NODE_SELECTORS_OPS == "OR" %}
              {% for selector in NODE_SELECTORS %}
              - matchExpressions:
                - key: {{selector.name}}
                  operator: In
                  values:
                  {% for vals in selector.value %}
                  - "{{vals}}"
                  {% endfor %}
              {% endfor %}
            {% else %}
              - matchExpressions:
              {% for selector in NODE_SELECTORS %}
                {% for vals in selector.value %}
                - key: {{selector.name}}
                  operator: In
                  values:
                  - "{{vals}}"
                {% endfor %}
              {% endfor %}
            {% endif %}
        {% endif %}
        containers:
        - name: registrar-leader
          image: docker.io/bundenth/kalavai-utils:latest
          command:
          - sh
          - -c
          - |
            echo "Waiting for model to be served..."
            echo "Namespace: "$VC_NAMESPACE;
            PS_HOST=`cat /etc/volcano/server.host`;
            /workspace/wait_for_service.sh --servers="$PS_HOST" --port=8080
            export MODEL_API_BASE="http://"$PS_HOST"."$VC_NAMESPACE":8080/v1";
            /workspace/start_point.sh \
              --litellm_kalavai_extras='{{litellm_kalavai_extras}}' \
              --litellm_access_group={{litellm_access_group}}
          env:
          - name: VC_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LITELLM_MODEL_NAME
          {% if model_name_override != "" %}
            value: "{{model_name_override}}"
          {% else %}
            value: "{{model_id}}"
          {% endif %}
          - name: LITELLM_BASE_URL
            value: {{litellm_base_url}}
          - name: LITELLM_KEY
            value: {{litellm_key}}
          - name: MODEL_ID
            value: {{model_id}}
          - name: DEPLOYMENT_ID
            value: {{deployment_id}}
          - name: PROVIDER
            value: hosted_vllm
          lifecycle:
            preStop:
              exec:
                command: 
                - sh
                - -c
                - |
                  /workspace/cleanup.sh
          resources:
            requests:
              cpu: 0.05
              memory: 0.05Gi
            limits:
              cpu: 0.05
              memory: 0.05Gi
        restartPolicy: OnFailure
{% endif %}
  - replicas: 1   # One ps pod specified
    name: server
    policies:
    - event: PodEvicted
      action: RestartJob
    - event: PodFailed
      action: RestartJob
    - event: TaskCompleted
      action: RestartJob
    - event: Unknown
      action: RestartJob
    template: # Definition of the ps pod
      terminationGracePeriodSeconds: 60
      metadata:
        labels:
          role: leader
          kalavai.job.name: {{deployment_id}}
      spec:
      {% if gpu_backend == "cuda" %}
        runtimeClassName: nvidia
      {% endif %}
      {% if NODE_SELECTORS %}
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
            {% if NODE_SELECTORS_OPS == "OR" %}
              {% for selector in NODE_SELECTORS %}
              - matchExpressions:
                - key: {{selector.name}}
                  operator: In
                  values:
                  {% for vals in selector.value %}
                  - "{{vals}}"
                  {% endfor %}
              {% endfor %}
            {% else %}
              - matchExpressions:
              {% for selector in NODE_SELECTORS %}
                {% for vals in selector.value %}
                - key: {{selector.name}}
                  operator: In
                  values:
                  - "{{vals}}"
                {% endfor %}
              {% endfor %}
            {% endif %}
        {% endif %}
        containers:
        - name: vllm-leader
          image: docker.io/bundenth/ray-vllm-{{gpu_backend}}:latest
          command:
          - sh
          - -c
          - |
            RAY_BACKEND_LOG_LEVEL=error /home/ray/workspace/ray_init.sh leader --ray_cluster_size={{workers}} --ray_object_store_memory={{memory * 500000000}};
            sleep 10;
          {% if gpu_backend == "cuda" %}
            nvidia-smi;
          {% else %}
            rocm-smi;
            python -c "import torch; print(torch.cuda.device_count(), torch.cuda.get_device_name(0))";
          {% endif %}
            ray status;
            # Run model
            echo "Total parallelism: {{workers * gpus}}";
            /home/ray/workspace/run_model.sh \
              --model_path="/home/ray/cache/{{model_id}}" \
              --model_id={{model_id}} \
              --model_name={{model_name_override}} \
              --extra='{{extra}}' \
              --template_url='{{template_url}}' \
              --tensor_parallel_size={{gpus}} \
              --pipeline_parallel_size={{workers}} \
              --tool_call_parser={{tool_call_parser}} \
              --lora_modules="{{lora_modules}}";
            exit 1
          env:
          - name: HF_TOKEN
            value: {{hf_token}}
          - name: LMCACHE_CHUNK_SIZE
            value: "{{lmcache_chunk_size}}"
          - name: LMCACHE_LOCAL_CPU
            value: "{{lmcache_local_cpu}}"
          - name: LMCACHE_MAX_LOCAL_CPU_SIZE
            value: "{{lmcache_max_local_cpu_size}}"
          - name: LMCACHE_MAX_LOCAL_DISK_SIZE
            value: "{{lmcache_max_local_disk_size}}"
          - name: LMCACHE_REMOTE_URL
            value: {{lmcache_remote_url}}
          - name: LMCACHE_LOCAL_DISK
            value: {{lmcache_local_disk}}
          # - name: HSA_OVERRIDE_GFX_VERSION
          #   value: "10.3.0"
          ports:
          - containerPort: 8080
            name: model-port
          - containerPort: 8265
            name: dashboard-port
          # this blocks internal traffic, which causes issues when tasks wait for each other
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          resources:
            requests:
              cpu: {{cpus}}
              memory: {{memory}}Gi
            {% if gpu_backend == "cuda" %}
              nvidia.com/gpu: {{gpus}}
            {% else %}
              amd.com/gpu: {{gpus}}
            {% endif %}
              ephemeral-storage: {{working_memory}}Gi
            limits:
              cpu: {{cpus}}
              memory: {{memory}}Gi
            {% if gpu_backend == "cuda" %}
              nvidia.com/gpu: {{gpus}}
              nvidia.com/gpumem-percentage: {{cuda_gpu_mem_percentage}}
            {% else %}
              amd.com/gpu: {{gpus}}
            {% endif %}
              ephemeral-storage: {{working_memory}}Gi
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - name: cache
              mountPath: /home/ray/cache
        volumes:
        - name: cache
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{memory * 0.5}}Gi
        restartPolicy: OnFailure
  - replicas: {{workers - 1}}
    name: worker
    policies:
    - event: PodEvicted
      action: RestartJob
    - event: PodFailed
      action: RestartJob
    - event: TaskCompleted
      action: RestartJob
    - event: Unknown
      action: RestartJob
    template: # Definition of worker pods
      terminationGracePeriodSeconds: 60
      metadata:
        labels:
          kalavai.job.name: {{deployment_id}}
      spec:
      {% if gpu_backend == "cuda" %}
        runtimeClassName: nvidia
      {% endif %}
      {% if NODE_SELECTORS %}
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
            {% if NODE_SELECTORS_OPS == "OR" %}
              {% for selector in NODE_SELECTORS %}
              - matchExpressions:
                - key: {{selector.name}}
                  operator: In
                  values:
                  {% for vals in selector.value %}
                  - "{{vals}}"
                  {% endfor %}
              {% endfor %}
            {% else %}
              - matchExpressions:
              {% for selector in NODE_SELECTORS %}
                {% for vals in selector.value %}
                - key: {{selector.name}}
                  operator: In
                  values:
                  - "{{vals}}"
                {% endfor %}
              {% endfor %}
            {% endif %}
        {% endif %}
        containers:
        - name: vllm-worker
          image: docker.io/bundenth/ray-vllm-{{gpu_backend}}:latest #v1.1.4
          command:
          - sh
          - -c
          - |
            PS_HOST=`cat /etc/volcano/server.host`;
          {% if gpu_backend == "cuda" %}
            nvidia-smi;
          {% else %}
            rocm-smi;
            python -c "import torch; print(torch.cuda.device_count(), torch.cuda.get_device_name(0))";
          {% endif %}
            RAY_BACKEND_LOG_LEVEL=error /home/ray/workspace/ray_init.sh worker --ray_address=$PS_HOST --ray_port=6379 --ray_object_store_memory={{memory * 500000000}} --ray_block=1
          env:
          - name: HF_TOKEN
            value: {{hf_token}}
          - name: LMCACHE_CHUNK_SIZE
            value: "{{lmcache_chunk_size}}"
          - name: LMCACHE_LOCAL_CPU
            value: "{{lmcache_local_cpu}}"
          - name: LMCACHE_MAX_LOCAL_CPU_SIZE
            value: "{{lmcache_max_local_cpu_size}}"
          - name: LMCACHE_MAX_LOCAL_DISK_SIZE
            value: "{{lmcache_max_local_disk_size}}"
          - name: LMCACHE_REMOTE_URL
            value: {{lmcache_remote_url}}
          - name: LMCACHE_LOCAL_DISK
            value: {{lmcache_local_disk}}
          # - name: HSA_OVERRIDE_GFX_VERSION
          #   value: "10.3.0"
          resources:
            requests:
              cpu: {{cpus}}
              memory: {{memory}}Gi
            {% if gpu_backend == "cuda" %}
              nvidia.com/gpu: {{gpus}}
            {% else %}
              amd.com/gpu: {{gpus}}
            {% endif %}
              ephemeral-storage: {{working_memory}}Gi
            limits:
              cpu: {{cpus}}
              memory: {{memory}}Gi
            {% if gpu_backend == "cuda" %}
              nvidia.com/gpu: {{gpus}}
              nvidia.com/gpumem-percentage: {{cuda_gpu_mem_percentage}}
            {% else %}
              amd.com/gpu: {{gpus}}
            {% endif %}
              ephemeral-storage: {{working_memory}}Gi
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - name: cache
              mountPath: /home/ray/cache
        volumes:
        - name: cache
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{memory * 0.5}}Gi
        restartPolicy: OnFailure
---
# deploy NodePort to expose model (if not using LiteLLM registration)
{% if litellm_key == "" %}
apiVersion: v1
kind: Service
metadata:
  name: {{deployment_id}}-service
  labels:
    # must have this!
    kalavai.job.name: {{deployment_id}}
spec:
  type: NodePort
  selector:
    role: leader
    kalavai.job.name: {{deployment_id}}
  ports:
    - name: main
      port: 8080
      targetPort: 8080
      protocol: TCP
    {% if nodeport != "" %}
      nodePort: {{nodeport}}
    {% endif %}
{% endif %}
