apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: {{deployment_id}}
  labels:
    # must have this label
    kalavai.job.name: {{deployment_id}}
spec:
  queue: default
  schedulerName: volcano
  plugins:
    env: []
    svc: ["--disable-network-policy=true"]
  maxRetries: {{max_retries}}
  tasks:
{% if litellm_key != "" %}
  - replicas: 1   # One ps pod specified
    name: registrar
    policies:
    - event: PodEvicted
      action: RestartTask
    - event: PodFailed
      action: RestartTask
    - event: TaskCompleted
      action: RestartTask
    - event: Unknown
      action: RestartTask
    template: # Definition of the ps pod
      terminationGracePeriodSeconds: 30 #give enough time to the preStop hook
      metadata:
        labels:
          kalavai.job.name: {{deployment_id}}
      spec:
      {% if NODE_SELECTORS %}
        nodeSelector:
        {% for selector in NODE_SELECTORS %}
          {{selector.name}}: {{selector.value}}
        {% endfor %}
      {% endif %}
        containers:
        - name: vllm-leader
          image: docker.io/bundenth/kalavai-utils:latest
          env:
          - name: VC_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          command:
          - sh
          - -c
          - |
            echo $VC_NAMESPACE;
            # wait for model to be served
            echo "Waiting for model service..."
            PS_HOST=`cat /etc/volcano/server.host`;
            /workspace/wait_for_service.sh --servers="$PS_HOST" --port=8080
            # Register model with LiteLLM
            PS_HOST=`cat /etc/volcano/server.host`;
            {% if model_name_override != "" %}
            LITELLM_MODEL_NAME="{{model_name_override}}";
            {% else %}
            LITELLM_MODEL_NAME="{{model_id}}";
            {% endif %}
            echo "Creating new entry on LiteLLM: (host: $PS_HOST) - (model id: $LITELLM_MODEL_NAME) - (job_id: {{deployment_id}})";
            API_BASE="http://"$PS_HOST"."$VC_NAMESPACE":8080/v1";
            /workspace/register_model.sh \
              --litellm_base_url={{litellm_base_url}} \
              --litellm_key={{litellm_key}} \
              --litellm_model_name="$LITELLM_MODEL_NAME" \
              --model_id="$LITELLM_MODEL_NAME" \
              --provider=hosted_vllm \
              --api_base=$API_BASE \
              --job_id={{deployment_id}} \
              --model_info='{"mode": "{{mode}}", "cpus": "{{cpus}}", "gpus": "{{gpus}}", "memory": "{{memory}}", "tensor_parallel_size": "{{gpus}}", "pipeline_parallel_size": "{{workers - 1}}"}'
          lifecycle:
            preStop:
              exec:
                command: 
                - sh
                - -c
                - |
                {% if model_name_override != "" %}
                  LITELLM_MODEL_NAME="{{model_name_override}}";
                {% else %}
                  LITELLM_MODEL_NAME="{{model_id}}";
                {% endif %}
                  MODEL_ID=$(python3 /workspace/get_litellm_id.py \
                    --litellm_url={{litellm_base_url}} \
                    --api_key={{litellm_key}} \
                    --job_id={{deployment_id}} \
                    --model_name="$LITELLM_MODEL_NAME");
                  curl -X POST "{{litellm_base_url}}/model/delete" \
                      -H 'Authorization: Bearer {{litellm_key}}' \
                      -H "accept: application/json" \
                      -H "Content-Type: application/json" \
                      -d '{ "id": "'$MODEL_ID'"}';
          resources:
            requests:
              cpu: 0.1
              memory: 0.1Gi
            limits:
              cpu: 0.1
              memory: 0.1Gi
        restartPolicy: OnFailure
{% endif %}
  - replicas: 1   # One ps pod specified
    name: server
    policies:
    - event: PodEvicted
      action: RestartJob
    - event: PodFailed
      action: RestartJob
    - event: TaskCompleted
      action: RestartJob
    - event: Unknown
      action: RestartJob
    template: # Definition of the ps pod
      metadata:
        annotations:
          # must have these annotations
          {{nouse_gputype}}
          {{use_gputype}}
        labels:
          role: leader
          kalavai.job.name: {{deployment_id}}
      spec:
      {% if gpu_backend == "cuda" %}
        runtimeClassName: nvidia
      {% endif %}
      {% if NODE_SELECTORS %}
        nodeSelector:
        {% for selector in NODE_SELECTORS %}
          {{selector.name}}: {{selector.value}}
        {% endfor %}
      {% endif %}
        containers:
        - name: vllm-leader
          image: docker.io/bundenth/ray-vllm-{{gpu_backend}}:latest
          command:
          - sh
          - -c
          - |
            RAY_BACKEND_LOG_LEVEL=error /home/ray/workspace/ray_init.sh leader --ray_cluster_size={{workers}} --ray_object_store_memory={{memory * 500000000}};
            sleep 10;
          {% if gpu_backend == "cuda" %}
            nvidia-smi;
          {% else %}
            rocm-smi;
            python -c "import torch; print(torch.cuda.device_count(), torch.cuda.get_device_name(0))";
          {% endif %}
            ray status;
            # Run model
            echo "Total parallelism: {{workers * gpus}}";
            /home/ray/workspace/run_model.sh \
              --model_path="/home/ray/cache/{{model_id}}" \
              --model_id={{model_id}} \
              --model_name={{model_name_override}} \
              --extra='{{extra}}' \
              --template_url='{{template_url}}' \
              --tensor_parallel_size={{gpus}} \
              --pipeline_parallel_size={{workers}} \
              --tool_call_parser={{tool_call_parser}} \
              --lora_modules="{{lora_modules}}";
            exit 1
          env:
          - name: HF_TOKEN
            value: {{hf_token}}
          - name: LMCACHE_CHUNK_SIZE
            value: "{{lmcache_chunk_size}}"
          - name: LMCACHE_LOCAL_CPU
            value: "{{lmcache_local_cpu}}"
          - name: LMCACHE_MAX_LOCAL_CPU_SIZE
            value: "{{lmcache_max_local_cpu_size}}"
          - name: LMCACHE_MAX_LOCAL_DISK_SIZE
            value: "{{lmcache_max_local_disk_size}}"
          - name: LMCACHE_REMOTE_URL
            value: {{lmcache_remote_url}}
          - name: LMCACHE_LOCAL_DISK
            value: {{lmcache_local_disk}}
          # - name: HSA_OVERRIDE_GFX_VERSION
          #   value: "10.3.0"
          ports:
          - containerPort: 8080
            name: model-port
          - containerPort: 8265
            name: dashboard-port
          # this blocks internal traffic, which causes issues when tasks wait for each other
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          resources:
            requests:
              cpu: {{cpus}}
              memory: {{memory}}Gi
            {% if gpu_backend == "cuda" %}
              nvidia.com/gpu: {{gpus}}
            {% else %}
              amd.com/gpu: {{gpus}}
            {% endif %}
              ephemeral-storage: {{working_memory}}Gi
            limits:
              cpu: {{cpus}}
              memory: {{memory}}Gi
            {% if gpu_backend == "cuda" %}
              nvidia.com/gpu: {{gpus}}
            {% else %}
              amd.com/gpu: {{gpus}}
            {% endif %}
              ephemeral-storage: {{working_memory}}Gi
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - name: cache
              mountPath: /home/ray/cache
        volumes:
        - name: cache
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{memory * 0.5}}Gi
        restartPolicy: OnFailure
  - replicas: {{workers - 1}}
    name: worker
    policies:
    - event: PodEvicted
      action: RestartJob
    - event: PodFailed
      action: RestartJob
    - event: TaskCompleted
      action: RestartJob
    - event: Unknown
      action: RestartJob
    template: # Definition of worker pods
      metadata:
        annotations:
          # must have these annotations
          {{nouse_gputype}}
          {{use_gputype}}
        labels:
          kalavai.job.name: {{deployment_id}}
      spec:
      {% if gpu_backend == "cuda" %}
        runtimeClassName: nvidia
      {% endif %}
      {% if NODE_SELECTORS %}
        nodeSelector:
        {% for selector in NODE_SELECTORS %}
          {{selector.name}}: {{selector.value}}
        {% endfor %}
      {% endif %}
        containers:
        - name: vllm-worker
          image: docker.io/bundenth/ray-vllm-{{gpu_backend}}:latest #v1.1.4
          command:
          - sh
          - -c
          - |
            PS_HOST=`cat /etc/volcano/server.host`;
          {% if gpu_backend == "cuda" %}
            nvidia-smi;
          {% else %}
            rocm-smi;
            python -c "import torch; print(torch.cuda.device_count(), torch.cuda.get_device_name(0))";
          {% endif %}
            RAY_BACKEND_LOG_LEVEL=error /home/ray/workspace/ray_init.sh worker --ray_address=$PS_HOST --ray_port=6379 --ray_object_store_memory={{memory * 500000000}} --ray_block=1
          env:
          - name: HF_TOKEN
            value: {{hf_token}}
          - name: LMCACHE_CHUNK_SIZE
            value: "{{lmcache_chunk_size}}"
          - name: LMCACHE_LOCAL_CPU
            value: "{{lmcache_local_cpu}}"
          - name: LMCACHE_MAX_LOCAL_CPU_SIZE
            value: "{{lmcache_max_local_cpu_size}}"
          - name: LMCACHE_MAX_LOCAL_DISK_SIZE
            value: "{{lmcache_max_local_disk_size}}"
          - name: LMCACHE_REMOTE_URL
            value: {{lmcache_remote_url}}
          - name: LMCACHE_LOCAL_DISK
            value: {{lmcache_local_disk}}
          # - name: HSA_OVERRIDE_GFX_VERSION
          #   value: "10.3.0"
          resources:
            requests:
              cpu: {{cpus}}
              memory: {{memory}}Gi
            {% if gpu_backend == "cuda" %}
              nvidia.com/gpu: {{gpus}}
            {% else %}
              amd.com/gpu: {{gpus}}
            {% endif %}
              ephemeral-storage: {{working_memory}}Gi
            limits:
              cpu: {{cpus}}
              memory: {{memory}}Gi
            {% if gpu_backend == "cuda" %}
              nvidia.com/gpu: {{gpus}}
            {% else %}
              amd.com/gpu: {{gpus}}
            {% endif %}
              ephemeral-storage: {{working_memory}}Gi
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - name: cache
              mountPath: /home/ray/cache
        volumes:
        - name: cache
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{memory * 0.5}}Gi
        restartPolicy: OnFailure
---
# deploy NodePort to expose model (if not using LiteLLM registration)
{% if litellm_key == "" %}
apiVersion: v1
kind: Service
metadata:
  name: {{deployment_id}}-service
  labels:
    # must have this!
    kalavai.job.name: {{deployment_id}}
spec:
  type: NodePort
  selector:
    role: leader
    kalavai.job.name: {{deployment_id}}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
    - port: 8265
      targetPort: 8265
      protocol: TCP
{% endif %}
