- name: deployment_name
  value: axolotl
  default: axolotl
  editable: true
  required: true
  description: "Name of the deployment job"

- name: workers
  value: 1
  default: 1
  editable: true
  required: true
  description: "Number of workers, corresponding to the number of nodes (or machines) that will be used to deploy the model"

- name: hf_token
  value: <token>
  default: null
  editable: true
  required: false
  description: "Huggingface access token, only required to load gated model weights"
