- name: deployment_name
  value: litellm
  default: litellm
  description: "Name of the deployment job"
  
- name: replicas
  value: "1"
  default: "1"
  description: "Number of replicas to deploy"

- name: master_key
  value: "sk-1234"
  default: "sk-1234"
  description: ""

- name: salt_key
  value: "sk-1234567890"
  default: "sk-1234567890"
  description: ""

- name: disable_admin_ui
  value: "False"
  default: "False"
  description: ""

- name: ui_username
  value: "admin"
  default: "admin"
  description: ""

- name: ui_password
  value: "mypassword"
  default: "mypassword"
  description: ""

- name: postgres_db
  value: "ps_db"
  default: "ps_db"
  description: "Storage name for the postgres database (backend)"

- name: postgres_user
  value: "ps_user"
  default: "ps_user"
  description: "Storage name for the postgres database (backend)"

- name: postgres_password
  value: "ps_password"
  default: "ps_password"
  description: "Storage name for the postgres database (backend)"

- name: cpus
  value: "2"
  default: "2"
  description: "CPUs per single worker (final one = cpus * num_workers)"

- name: memory
  value: "2"
  default: "2"
  description: "RAM memory per single worker (final one = memory * num_workers)"

- name: langfuse_public_key
  value: "pk-lf-252180de-f7b9-4ef4-9d43-30529c43d78e"
  default: "sk-1234567890"
  description: "Langfuse public key"

- name: langfuse_secret_key
  value: "sk-lf-7af5b272-9bee-4c4e-8c1c-57053c9abedd"
  default: "sk-1234567890"
  description: "Langfuse secret key"

- name: langfuse_host
  value: "https://cloud.langfuse.com"
  default: "https://cloud.langfuse.com"
  description: "Langfuse host"

  